// ===== SHARED EVENT DATA =====
// Single source of truth for all hardcoded events.
// Loaded by calendar.html, m/calendar.html, and event.html.

var EVENTS = [
  // MUSIC FOR PEACE CONCERTS
  {
    id: 'mfp-violin',
    type: 'concert',
    title: 'Music for Peace: Carnatic Violin & Mridangam',
    desc: 'An evening of South Indian classical music with Shriram Rajagopalan (violin) and Keerthy Raghavan (mridangam). Intricate melodic structures and rhythmic complexity in a contemplative setting.',
    date: '2026-04-11',
    dateLabel: 'Saturday, April 11',
    time: '7:00 - 9:00 PM',
    venue: 'Satsang Room',
    price: '$40',
    badge: 'Apr 11',
    img: 'images/2026/03/Violin-Concert-April-11-2026-Shriram-Rajagopalan.jpg',
    featured: true
  },
  {
    id: 'spring-cleanse',
    type: 'retreat',
    title: 'Spring Cleanse Ayurveda Retreat',
    desc: 'Five days of cellular detox, mindful dietary choices, and holistic rejuvenation with Savita Leah Young. Ayurvedic cleanse addressing fatigue, hormonal balance, seasonal allergies, and weight.',
    date: '2026-04-02',
    dateLabel: 'April 2 - 6',
    time: '5 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Apr 2',
    img: 'images/2025/01/Blog-Post-picture-horizontal-1200-x-630-1.jpg'
  },
  {
    id: 'april-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Open to all genders, races, and yoga levels. Asana classes, breathwork, meditation, nature time, and lacto-vegetarian meals on 69 acres.',
    date: '2026-04-16',
    dateLabel: 'April 16 - 19',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Apr 16',
    img: 'images/2024/11/Blog-Post-picture-horizontal-1200-x-630-4.png'
  },
  {
    id: 'agni-protocol',
    type: 'retreat',
    title: 'Agni Protocol - Spring Detox Retreat',
    desc: 'Holistic Ayurvedic detox with Vd. Matheus Macedo (Vida Veda), Ishwarya Chaitanya (yoga), and Maria Marquez (movement). Four Pillars of Health, vegan meals, cleansing practices, silence.',
    date: '2026-04-23',
    dateLabel: 'April 23 - 26',
    time: '4 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Apr 23',
    img: 'images/2025/11/Agni-Protocol.jpg'
  },
  {
    id: 'sound-bath',
    type: 'concert',
    title: 'Sound Bath & Meditation with Farhad Khan',
    desc: 'Crystal bowls, gongs, and chimes for stress release, enhanced concentration, and chakra balancing. Over two decades of healing practice.',
    date: '2026-05-13',
    dateLabel: 'Tuesday, May 13',
    time: '7:30 - 8:30 PM',
    venue: 'Salt Spring Centre of Yoga',
    price: 'By Donation',
    badge: 'May 13',
    img: 'images/2025/11/SoundBath-SaltSpring.png'
  },
  {
    id: 'may-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'A weekend of yoga, meditation, nature walks, and nourishing vegetarian meals at the Centre.',
    date: '2026-05-08',
    dateLabel: 'May 8 - 10',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'May 8',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'nature-nurture-may',
    type: 'retreat',
    title: 'Nature & Nurture: Heal Through Yoga',
    desc: 'Ancient yogic techniques and philosophy for self-healing with Ishwarya Chaitanya. Hatha yoga, Sivananda tradition, yoga therapy. Set in a forested ecosystem.',
    date: '2026-05-14',
    dateLabel: 'May 14 - 17',
    time: '4 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'May 14',
    img: 'images/2025/08/519270511_18512460514049610_251173067301957564_n.jpg'
  },
  {
    id: 'june-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Three nights of yoga, breathwork, meditation, and community in the heart of summer.',
    date: '2026-06-18',
    dateLabel: 'June 18 - 21',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Jun 18',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'mfp-akhil',
    type: 'concert',
    title: 'Music for Peace: Akhil Jobanputra & Tihai Ensemble',
    desc: 'Hindustani classical concert featuring CBC\'s "30 under 30" vocalist Akhil Jobanputra with Mohan Bhide (harmonium) and Hriday Buddhdev (tabla). Expansive ragas and spontaneous improvisation.',
    date: '2026-06-27',
    dateLabel: 'Saturday, June 27',
    time: 'Doors 6:30 PM, Concert 7:00 - 9:00 PM',
    venue: 'Pond Dome',
    price: '$40',
    badge: 'Jun 27',
    img: 'images/2022/03/Grounding-with-music.jpg'
  },
  {
    id: 'july-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Mid-summer retreat with daily yoga, meditation, organic meals, and time in nature.',
    date: '2026-07-16',
    dateLabel: 'July 16 - 19',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Jul 16',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'mfp-deepak',
    type: 'concert',
    title: 'Music for Peace: Deepak Ram - Bansuri Flute',
    desc: 'Internationally celebrated bansuri master Deepak Ram performs Indian classical music on the bamboo flute. Deeply expressive and meditative sound.',
    date: '2026-08-01',
    dateLabel: 'Saturday, August 1',
    time: 'Doors 6:30 PM, Concert 7:00 - 9:00 PM',
    venue: 'Satsang Room',
    price: '$40',
    badge: 'Aug 1',
    img: 'images/2022/08/Kirtan.jpg'
  },
  {
    id: 'aug-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'Late summer weekend retreat with yoga, meditation, and organic vegetarian meals.',
    date: '2026-08-28',
    dateLabel: 'August 28 - 30',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Aug 28',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'sep-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'Autumn weekend at the Centre with daily practice, nature walks, and nourishing meals.',
    date: '2026-09-18',
    dateLabel: 'September 18 - 20',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Sep 18',
    img: 'images/2024/11/FALL-SCHEDULE-5.png'
  },
  {
    id: 'nature-nurture-oct',
    type: 'retreat',
    title: 'Nature & Nurture: Heal Through Yoga',
    desc: 'Autumn edition with Ishwarya Chaitanya. Ancient yogic techniques for self-healing, set in the Centre\'s forested ecosystem.',
    date: '2026-10-02',
    dateLabel: 'October 2 - 4',
    time: '3 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Oct 2',
    img: 'images/2025/08/519270511_18512460514049610_251173067301957564_n.jpg'
  },
  {
    id: 'oct-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Three nights of autumn practice, meditation, and organic meals surrounded by fall colours.',
    date: '2026-10-15',
    dateLabel: 'October 15 - 18',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Oct 15',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'soulful-silence',
    type: 'retreat',
    title: 'Soulful Silence Meditation Retreat',
    desc: 'Four-day silent retreat with Farhad Khan. Daily guided meditation, gentle yoga, restorative yoga, somatic stretch, pranayama, sound baths, Yoga Nidra, forest walking meditation, and kirtan. Includes a Khan Wellness Travel Pack (valued at $300 CAD).',
    date: '2026-10-22',
    dateLabel: 'October 22 - 25',
    time: '4 days / 3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Oct 22',
    img: 'images/2025/11/Soulful-Silence-Meditation-Retreat-Farhad-Khan-.jpg',
    featured: true
  },
  {
    id: 'nov-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'Late autumn weekend retreat with yoga, meditation, and warm vegetarian meals.',
    date: '2026-11-13',
    dateLabel: 'November 13 - 15',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Nov 13',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'nov-retreat-3',
    type: 'retreat',
    title: 'Winter Yoga & Wellness Retreat - 3 Days',
    desc: 'Pre-winter retreat to ground and restore. Yoga, breathwork, meditation, and community.',
    date: '2026-11-26',
    dateLabel: 'November 26 - 29',
    time: '3 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Nov 26',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  }
];

// Each event's URL is its dedicated detail page
EVENTS.forEach(function(e) { e.url = 'event.html?id=' + e.id; });
