// ===== SHARED EVENT DATA =====
// Single source of truth for all hardcoded events.
// Loaded by calendar.html, m/calendar.html, and event.html.

var EVENTS = [
  // MUSIC FOR PEACE CONCERTS
  {
    id: 'mfp-violin',
    type: 'concert',
    title: 'Music for Peace: Carnatic Violin & Mridangam',
    desc: 'An evening of South Indian classical music with Shriram Rajagopalan (violin) and Keerthy Raghavan (mridangam). Intricate melodic structures and rhythmic complexity in a contemplative setting.',
    date: '2026-04-11',
    dateLabel: 'Saturday, April 11',
    time: '7:00 - 9:00 PM',
    venue: 'Satsang Room',
    price: '$40',
    badge: 'Apr 11',
    img: 'images/2026/03/Violin-Concert-April-11-2026-Shriram-Rajagopalan.jpg',
    featured: true
  },
  {
    id: 'spring-cleanse',
    type: 'retreat',
    title: 'Spring Cleanse Ayurveda Retreat',
    desc: 'Five days of cellular detox, mindful dietary choices, and holistic rejuvenation with Savita Leah Young. Ayurvedic cleanse addressing fatigue, hormonal balance, seasonal allergies, and weight.',
    date: '2026-04-02',
    dateLabel: 'April 2 - 6',
    time: '5 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Apr 2',
    img: 'images/2025/01/Blog-Post-picture-horizontal-1200-x-630-1.jpg'
  },
  {
    id: 'april-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Open to all genders, races, and yoga levels. Asana classes, breathwork, meditation, nature time, and lacto-vegetarian meals on 69 acres.',
    date: '2026-04-16',
    dateLabel: 'April 16 - 19',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Apr 16',
    img: 'images/2024/11/Blog-Post-picture-horizontal-1200-x-630-4.png'
  },
  {
    id: 'agni-protocol',
    type: 'retreat',
    title: 'Agni Protocol - Spring Detox Retreat',
    desc: 'Holistic Ayurvedic detox with Vd. Matheus Macedo (Vida Veda), Ishwarya Chaitanya (yoga), and Maria Marquez (movement). Four Pillars of Health, vegan meals, cleansing practices, silence.',
    date: '2026-04-23',
    dateLabel: 'April 23 - 26',
    time: '4 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Apr 23',
    img: 'images/2025/11/Agni-Protocol.jpg'
  },
  {
    id: 'sound-bath',
    type: 'concert',
    title: 'Sound Bath & Meditation with Farhad Khan',
    desc: 'Crystal bowls, gongs, and chimes for stress release, enhanced concentration, and chakra balancing. Over two decades of healing practice.',
    date: '2026-05-13',
    dateLabel: 'Tuesday, May 13',
    time: '7:30 - 8:30 PM',
    venue: 'Salt Spring Centre of Yoga',
    price: 'By Donation',
    badge: 'May 13',
    img: 'images/2025/11/SoundBath-SaltSpring.png'
  },
  {
    id: 'may-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'A weekend of yoga, meditation, nature walks, and nourishing vegetarian meals at the Centre.',
    date: '2026-05-08',
    dateLabel: 'May 8 - 10',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'May 8',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'nature-nurture-may',
    type: 'retreat',
    title: 'Nature & Nurture: Heal Through Yoga',
    desc: 'Ancient yogic techniques and philosophy for self-healing with Ishwarya Chaitanya. Hatha yoga, Sivananda tradition, yoga therapy. Set in a forested ecosystem.',
    date: '2026-05-14',
    dateLabel: 'May 14 - 17',
    time: '4 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'May 14',
    img: 'images/2025/08/519270511_18512460514049610_251173067301957564_n.jpg'
  },
  {
    id: 'june-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Three nights of yoga, breathwork, meditation, and community in the heart of summer.',
    date: '2026-06-18',
    dateLabel: 'June 18 - 21',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Jun 18',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'mfp-akhil',
    type: 'concert',
    title: 'Music for Peace: Akhil Jobanputra & Tihai Ensemble',
    desc: 'Hindustani classical concert featuring CBC\'s "30 under 30" vocalist Akhil Jobanputra with Mohan Bhide (harmonium) and Hriday Buddhdev (tabla). Expansive ragas and spontaneous improvisation.',
    date: '2026-06-27',
    dateLabel: 'Saturday, June 27',
    time: 'Doors 6:30 PM, Concert 7:00 - 9:00 PM',
    venue: 'Pond Dome',
    price: '$40',
    badge: 'Jun 27',
    img: 'images/2022/03/Grounding-with-music.jpg'
  },
  {
    id: 'july-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Mid-summer retreat with daily yoga, meditation, organic meals, and time in nature.',
    date: '2026-07-16',
    dateLabel: 'July 16 - 19',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Jul 16',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'mfp-deepak',
    type: 'concert',
    title: 'Music for Peace: Deepak Ram - Bansuri Flute',
    desc: 'Internationally celebrated bansuri master Deepak Ram performs Indian classical music on the bamboo flute. Deeply expressive and meditative sound.',
    date: '2026-08-01',
    dateLabel: 'Saturday, August 1',
    time: 'Doors 6:30 PM, Concert 7:00 - 9:00 PM',
    venue: 'Satsang Room',
    price: '$40',
    badge: 'Aug 1',
    img: 'images/2022/08/Kirtan.jpg'
  },
  {
    id: 'aug-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'Late summer weekend retreat with yoga, meditation, and organic vegetarian meals.',
    date: '2026-08-28',
    dateLabel: 'August 28 - 30',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Aug 28',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'sep-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'Autumn weekend at the Centre with daily practice, nature walks, and nourishing meals.',
    date: '2026-09-18',
    dateLabel: 'September 18 - 20',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Sep 18',
    img: 'images/2024/11/FALL-SCHEDULE-5.png'
  },
  {
    id: 'nature-nurture-oct',
    type: 'retreat',
    title: 'Nature & Nurture: Heal Through Yoga',
    desc: 'Autumn edition with Ishwarya Chaitanya. Ancient yogic techniques for self-healing, set in the Centre\'s forested ecosystem.',
    date: '2026-10-02',
    dateLabel: 'October 2 - 4',
    time: '3 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Oct 2',
    img: 'images/2025/08/519270511_18512460514049610_251173067301957564_n.jpg'
  },
  {
    id: 'oct-retreat-3',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 3 Nights',
    desc: 'Three nights of autumn practice, meditation, and organic meals surrounded by fall colours.',
    date: '2026-10-15',
    dateLabel: 'October 15 - 18',
    time: '3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Oct 15',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'soulful-silence',
    type: 'retreat',
    title: 'Soulful Silence Meditation Retreat',
    desc: 'Four-day silent retreat with Farhad Khan. Daily guided meditation, gentle yoga, restorative yoga, somatic stretch, pranayama, sound baths, Yoga Nidra, forest walking meditation, and kirtan. Includes a Khan Wellness Travel Pack (valued at $300 CAD).',
    date: '2026-10-22',
    dateLabel: 'October 22 - 25',
    time: '4 days / 3 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Oct 22',
    img: 'images/2025/11/Soulful-Silence-Meditation-Retreat-Farhad-Khan-.jpg',
    featured: true
  },
  {
    id: 'nov-retreat-2',
    type: 'retreat',
    title: 'Yoga & Wellness Retreat - 2 Nights',
    desc: 'Late autumn weekend retreat with yoga, meditation, and warm vegetarian meals.',
    date: '2026-11-13',
    dateLabel: 'November 13 - 15',
    time: '2 nights',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Nov 13',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  {
    id: 'nov-retreat-3',
    type: 'retreat',
    title: 'Winter Yoga & Wellness Retreat - 3 Days',
    desc: 'Pre-winter retreat to ground and restore. Yoga, breathwork, meditation, and community.',
    date: '2026-11-26',
    dateLabel: 'November 26 - 29',
    time: '3 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Nov 26',
    img: 'images/2023/11/Program-House-with-flowers-resized.png'
  },
  // ===== YEAR-ROUND PROGRAM DESCRIPTIONS =====
  {
    id: 'yoga-wellness-weekends',
    type: 'retreat',
    title: 'Yoga & Wellness Weekends',
    desc: 'Two or three night retreats open to all levels. A full immersion in asana, breathwork, meditation, nature walks, and freshly prepared vegetarian meals. Led by resident Karma Yogis and visiting teachers.',
    date: '2026-04-16',
    dateLabel: 'Monthly, April through November',
    time: 'Weekends',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Ongoing',
    img: 'images/2021/11/retreat-1.jpg',
    longDesc: 'Yoga & Wellness Weekends are the Centre\'s most accessible retreat format, running monthly from April through November. Each weekend retreat offers a full immersion in asana, breathwork, meditation, nature walks, and freshly prepared lacto-vegetarian meals. The atmosphere is warm and welcoming, with resident Karma Yogis and visiting teachers guiding the practice. Two-night and three-night options are available.'
  },
  {
    id: 'breath-raja-yoga',
    type: 'retreat',
    title: 'Breath as a Gateway to Raja Yoga',
    desc: 'Seven-day Akhanda Yoga immersion with Dr. Yogrishi Vishvketu. Rooted in Himalayan traditions, this intensive focuses on pranayama mastery, meditation, and the subtler limbs of classical yoga.',
    date: '2026-06-10',
    dateLabel: 'June 10 - 16',
    time: '7 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Jun 10',
    img: 'images/2021/12/serene.jpg',
    longDesc: 'Dr. Yogrishi Vishvketu, founder of the Akhanda Yoga tradition, brings decades of teaching from the Himalayan lineage for this seven-day intensive. The focus is on pranayama (breath mastery), meditation, and the subtler limbs of classical yoga. Students will experience daily asana practice, philosophical study, mantra, and extended periods of silent practice. A rare opportunity to study directly with a master teacher in the lineage of Swami Rama.'
  },
  {
    id: 'ayurveda-more-from-life',
    type: 'retreat',
    title: 'Ayurveda & Yoga: I Want More From Life',
    desc: 'Five-day intensive integrating Ayurveda, psychology, somatic medicine, and nonviolent communication. For those ready to examine their patterns and reclaim energy for what matters most.',
    date: '2026-09-15',
    dateLabel: 'September 2026',
    time: '5 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Sep 2026',
    img: 'images/2021/10/indian-spices-1.jpg',
    longDesc: 'This five-day intensive weaves Ayurveda, psychology, somatic medicine, and nonviolent communication into a retreat designed for people ready to examine their patterns and reclaim energy for what matters most. The program includes Ayurvedic consultations and treatments, yoga practice, group process work, and quiet time to integrate. Suitable for those at any stage of the path who feel called to go deeper.'
  },
  {
    id: 'yoga-intensive-2026',
    type: 'retreat',
    title: 'Yoga Intensive Program',
    desc: 'Five days of concentrated practice and study. Approved for Yoga Alliance continuing education hours. Suitable for teachers and serious students looking to deepen their understanding of classical yoga.',
    date: '2026-07-02',
    dateLabel: 'July 2 - 6',
    time: '5 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Jul 2026',
    img: 'images/2021/11/programs-retreats.jpg',
    longDesc: 'The Yoga Intensive Program is a five-day immersion designed for yoga teachers and serious students who want to deepen their understanding of classical yoga. The program is approved for Yoga Alliance continuing education hours. Expect multiple daily asana sessions, pranayama and meditation practice, philosophical study of the Yoga Sutras, and group discussions. Dive Deep, Rise Strong.',
    relatedPage: 'yoga-intensive.html'
  },
  {
    id: 'going-deeper-silent',
    type: 'retreat',
    title: 'Going Deeper Silent Retreat',
    desc: 'A profound silent retreat created by Baba Hari Dass. Covered windows, minimal light, and a cave-like atmosphere designed for deep inner exploration. Led by Chetna Tracy Boyd and Gita Tanya Roberts.',
    date: '2026-11-18',
    dateLabel: 'November 18 - 22',
    time: '5 days',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Nov 18',
    img: 'images/2022/03/Forest-Canopy-from-the-ground-1024x683-1.jpg',
    longDesc: 'Going Deeper is a profound silent retreat format created by Baba Hari Dass. The retreat space features covered windows and minimal light, creating a cave-like atmosphere designed to support deep inner exploration. Led by senior teachers Chetna Tracy Boyd and Gita Tanya Roberts, the retreat includes meditation, gentle yoga, pranayama, and extended periods of silence. An opportunity for experienced practitioners to drop beneath the surface of daily life.'
  },
  {
    id: 'annual-community-retreat',
    type: 'retreat',
    title: 'Annual Community Yoga Retreat',
    desc: "A 50-year tradition. Family-friendly, multi-day gathering featuring diverse yoga styles, workshops, kirtan, meals, and community. The Centre's flagship event, drawing practitioners from across Canada and beyond.",
    date: '2026-08-15',
    dateLabel: 'August 2026',
    time: 'Multi-day',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Registration opens later in 2026',
    badge: 'Aug 2026',
    img: 'images/2022/05/ACYR-Group-Peace.jpg',
    longDesc: 'The Annual Community Yoga Retreat (ACYR) is a 50-year tradition and the Centre\'s flagship event. A family-friendly, multi-day gathering that brings practitioners from across Canada and beyond to practice together on the Centre land. Expect diverse yoga styles, workshops, kirtan, shared meals, and deep community. Children and teens have their own dedicated programming. Registration opens later in 2026.',
    relatedPage: 'acyr.html'
  },
  {
    id: 'personal-retreats',
    type: 'retreat',
    title: 'Personal Retreats',
    desc: 'Self-directed schedule on 69 acres of sacred land. Light self-serve breakfast, two cooked vegetarian meals per day, and a 24/7 tea bar. Access community yoga classes and ceremonies, the library and lounge, forested walking trails, and a swimming lake.',
    date: '',
    dateLabel: 'Available year-round',
    time: 'Flexible duration',
    venue: 'Salt Spring Centre of Yoga',
    price: 'Inquire',
    badge: 'Year-round',
    img: 'images/2025/12/Personal-Retreat-Instagram-May-2022.jpg',
    longDesc: 'Personal Retreats offer a self-directed alternative to structured programming. Guests set their own rhythm on 69 acres of sacred land, with light self-serve breakfast, two cooked vegetarian meals per day, and a 24/7 tea bar included. You\'ll have access to community yoga classes and ceremonies, the library and lounge, forested walking trails, and a swimming lake. Book through Retreat Guru.',
    bookUrl: 'https://saltspringcentre.secure.retreat.guru'
  }
];

// ===== WEEKLY CLASSES =====
var CLASSES_DATA = [
  {
    id: 'class-hatha-dorothy',
    type: 'class',
    title: 'Hatha Yoga with Dorothy',
    teacher: 'Dorothy Price',
    schedule: 'Monday & Thursday, 4:30 - 5:45 PM',
    days: ['Monday', 'Thursday'],
    time: '4:30 - 5:45 PM',
    price: '$118 - $134 / 8-class pass',
    dropIn: 'Drop-in welcome',
    format: 'In-person',
    location: 'Garden House Yoga Studio',
    level: 'All levels',
    desc: 'Classical Hatha yoga suitable for all levels. A grounding mid-week and end-of-week practice led by a long-time Centre teacher.',
    longDesc: 'Dorothy Price brings decades of practice to this accessible Hatha class. Expect a careful sequence of warming postures, standing and seated asana, floor work, and a brief relaxation. The emphasis is on alignment, breath, and listening to the body. Students of all levels and experience are welcome.',
    img: 'images/2021/12/Class-3-1024x610-1.jpg'
  },
  {
    id: 'class-yoga-flow-john',
    type: 'class',
    title: 'Yoga Flow with John Howe',
    teacher: 'John Howe',
    schedule: 'Saturday, 9:30 - 10:30 AM',
    days: ['Saturday'],
    time: '9:30 - 10:30 AM',
    price: '$100 / 8 classes &middot; $15 drop-in',
    format: 'In-person',
    location: 'Garden House Yoga Studio',
    level: 'All levels (modifications offered)',
    desc: 'A flowing, breath-led Saturday morning practice. Energizing and accessible, with modifications offered for all levels.',
    longDesc: 'John Howe guides a gentle vinyasa-style flow to start your Saturday. Breath leads movement through sun salutations, standing postures, balancing work, and seated stretches. Modifications are offered so students at every level can practice comfortably alongside one another.',
    img: 'images/2021/11/retreat-2.jpg'
  },
  {
    id: 'class-sacred-sunday',
    type: 'class',
    title: 'Sacred Sunday Eco-Yoga with Cara Graci',
    teacher: 'Cara Graci',
    schedule: 'Sunday, 11:00 AM - 12:15 PM',
    days: ['Sunday'],
    time: '11:00 AM - 12:15 PM',
    price: 'By donation',
    format: 'Outdoor',
    location: 'Pond Dome',
    level: 'All levels',
    desc: 'Practice outdoors at the Pond Dome, surrounded by the sounds and rhythms of the natural world. A meditative, earth-connected experience.',
    longDesc: 'Eco-Yoga with Cara Graci takes place at the Pond Dome, a beautiful open-air space on the Centre grounds. Practice unfolds alongside birdsong, breeze, and the living presence of the land. The class combines gentle asana, breathwork, and moments of stillness that deepen connection to nature and self.',
    img: 'images/2022/03/pond-dome-2.jpg'
  },
  {
    id: 'class-gentle-hatha-repair',
    type: 'class',
    title: 'Gentle Hatha Repair with Cara Graci',
    teacher: 'Cara Graci',
    schedule: 'Wednesday, 11:00 AM - 12:15 PM',
    days: ['Wednesday'],
    time: '11:00 AM - 12:15 PM',
    price: 'By donation',
    format: 'Online / Zoom',
    level: 'Gentle, therapeutic',
    desc: 'A slow, therapeutic practice designed to restore and repair. Emphasis on gentle movement, breath, and deep rest. Available in-person and on Zoom.',
    longDesc: 'Gentle Hatha Repair is a slow, restorative practice with Cara Graci, created for students who need a soft entry point or who are recovering from injury, illness, or fatigue. The class combines supported postures, breath awareness, and extended rest. Props are encouraged. Available online via Zoom.',
    img: 'images/2025/12/Nature-and-Nurture-Webpage-12.jpg'
  },
  {
    id: 'class-meditation-mellow',
    type: 'class',
    title: 'Meditation & Mellow Yoga with Cara Graci',
    teacher: 'Cara Graci',
    schedule: 'Thursday, 4:30 - 5:30 PM',
    days: ['Thursday'],
    time: '4:30 - 5:30 PM',
    price: 'Free / donation',
    format: 'Online / Zoom',
    level: 'All levels',
    desc: 'A quiet Thursday practice combining gentle movement with seated meditation. Suitable for beginners and experienced practitioners alike.',
    longDesc: 'Meditation & Mellow Yoga is a quiet Thursday practice blending slow movement with seated meditation. Cara Graci guides the session online via Zoom. The class is gentle enough for beginners and rich enough for experienced practitioners looking to deepen their sit.',
    img: 'images/2014/11/Babaji-meditating.jpg'
  },
  {
    id: 'class-mindfulness-nature',
    type: 'class',
    title: 'Mindfulness in Nature Eco-Yoga with Cara Graci',
    teacher: 'Cara Graci',
    schedule: 'Friday, 4:30 - 5:45 PM',
    days: ['Friday'],
    time: '4:30 - 5:45 PM',
    price: 'By donation',
    format: 'Outdoor',
    location: 'Forest & meadow',
    level: 'All levels',
    desc: 'Outdoor yoga practice cultivating presence through nature. Breath, movement, and stillness in the forest and meadow.',
    longDesc: 'Mindfulness in Nature Eco-Yoga takes practice outside, into the forest and meadow of the Centre grounds. Cara Graci weaves gentle movement, breath, and stillness into a practice that cultivates presence with the living world. Please dress for the weather and bring a mat or blanket.',
    img: 'images/2022/03/Forest-Canopy-from-the-ground-1024x683-1.jpg'
  },
  {
    id: 'class-yoga-sutras',
    type: 'class',
    title: 'Yoga Sutras Study Group',
    teacher: 'Yogeshwar (Will Humphrey)',
    schedule: 'Monday, 7:00 - 8:00 PM',
    days: ['Monday'],
    time: '7:00 - 8:00 PM',
    price: 'By donation',
    format: 'Online / Zoom',
    level: 'All welcome',
    desc: "Weekly study of Patanjali's Yoga Sutras with Yogeshwar (Will Humphrey). A careful, verse-by-verse exploration of yoga's foundational philosophical text.",
    longDesc: "Join Yogeshwar (Will Humphrey) for a weekly study of Patanjali's Yoga Sutras. Each session moves verse by verse through the text, using Baba Hari Dass's commentaries as a guide. The group reads translations aloud, discusses meaning, and explores how these ancient teachings apply to practice and daily life. No prior study required.",
    img: 'images/2022/03/Baba-Hari-Dass-w-Chalkboard-1970s.jpg'
  },
  {
    id: 'class-bhagavad-gita',
    type: 'class',
    title: 'Bhagavad Gita Study Group',
    teacher: 'Mahavir',
    schedule: 'Tuesday, 7:30 - 8:30 PM',
    days: ['Tuesday'],
    time: '7:30 - 8:30 PM',
    price: 'By donation',
    format: 'Online / Zoom',
    level: 'All welcome',
    desc: 'Weekly reading and discussion of the Bhagavad Gita led by Mahavir, using the translations and commentaries of Baba Hari Dass.',
    longDesc: "Mahavir leads this weekly scripture study exploring the Bhagavad Gita through Baba Hari Dass's translations and commentaries. The group reads passages together, chants verses in Sanskrit, and discusses the Gita's teachings on dharma, devotion, and selfless action. Beginning and seasoned students are both welcome.",
    img: 'images/2023/03/Babaji-teaching-black-and-white.jpg'
  },
  {
    id: 'class-sadhana',
    type: 'class',
    title: 'Sadhana for Continuing Practitioners',
    teacher: 'Centre Community',
    schedule: 'Sunday, 7:30 - 8:40 AM',
    days: ['Sunday'],
    time: '7:30 - 8:40 AM',
    price: 'Free',
    format: 'Online / Zoom',
    level: 'Experienced practitioners',
    desc: 'Early Sunday morning practice for experienced students. A dedicated time for deepening personal sadhana within a supportive group container.',
    longDesc: "Sadhana for Continuing Practitioners is an early Sunday morning container for students with an established personal practice. The session combines pranayama and seated meditation in silence, supported by the presence of a committed group. Open to experienced practitioners familiar with the Centre's tradition.",
    img: 'images/2021/12/DawnOverTheGarden-small-1.jpg'
  }
];

// ===== COMMUNITY GATHERINGS =====
var COMMUNITY_DATA = [
  {
    id: 'community-sunday-satsang',
    type: 'community',
    title: 'Sunday Satsang',
    schedule: 'Sunday, 2:00 - 3:30 PM',
    days: ['Sunday'],
    time: '2:00 - 3:30 PM',
    price: 'Free (donations welcome)',
    format: 'Hybrid: in-person + Zoom',
    location: 'Satsang Room',
    desc: 'The heart of the weekly community gathering. Kirtan, meditation, spiritual readings, and shared silence.',
    longDesc: "Satsang means 'union of truth.' Sunday Satsang is the heart of the Centre's weekly community life. The gathering includes kirtan (devotional chanting), meditation, readings from Baba Hari Dass and yogic scripture, and shared silence. Held in the Satsang Room with a simultaneous Zoom feed for those joining from afar. All are welcome regardless of background or belief.",
    img: 'images/2023/04/Other-ways-to-help-Program-in-the-Satsang-Room.jpg'
  },
  {
    id: 'community-vancouver-satsang',
    type: 'community',
    title: 'Vancouver Satsang',
    schedule: 'Wednesday, 6:30 - 8:00 PM',
    days: ['Wednesday'],
    time: '6:30 - 8:00 PM',
    price: 'Free (donations welcome)',
    format: 'Online / Zoom',
    desc: 'A mid-week online gathering for the extended community. Yoga Sutra study followed by kirtan.',
    longDesc: "Vancouver Satsang is a mid-week online gathering rooted in the Centre's community in Vancouver and extending across the country. Each session begins with a brief Yoga Sutra study and closes with kirtan. A way to stay connected to the Centre's teachings between visits.",
    img: 'images/2022/11/Online-yoga.jpg'
  },
  {
    id: 'community-kirtan-class',
    type: 'community',
    title: 'Kirtan Class',
    schedule: 'Thursday, 7:00 - 8:30 PM',
    days: ['Thursday'],
    time: '7:00 - 8:30 PM',
    price: 'Pay-what-you-can ($20 suggested)',
    format: 'In-person',
    location: 'Satsang Room',
    note: 'Currently paused for summer. Check calendar for return date.',
    desc: 'Learn to chant, lead kirtan, and play harmonium. A welcoming space for beginners and experienced chanters.',
    longDesc: "Kirtan Class is a welcoming space to learn the practice of call-and-response devotional chanting. Open to complete beginners and experienced chanters alike, the class covers Sanskrit pronunciation, harmonium basics, leading kirtan, and the history and spirit of the bhakti tradition. Currently on pause for the summer months - check the calendar for the return date.",
    img: 'images/2022/03/Grounding-with-music.jpg'
  },
  {
    id: 'community-daily-arati',
    type: 'community',
    title: 'Daily Arati',
    schedule: 'Daily, 6:45 - 7:15 AM',
    days: ['Daily'],
    time: '6:45 - 7:15 AM',
    price: 'Free',
    format: 'In-person',
    location: 'The Temples',
    desc: 'The day begins with Arati, a lamp ceremony accompanied by mantras, prayers, and songs. A beautiful, brief ritual that sets the tone for the morning.',
    longDesc: "Arati is the traditional lamp ceremony that opens the day at the Centre. Held each morning at the temples, the ritual involves offerings of light, incense, and song, accompanied by mantras and prayers. Visitors are warmly welcomed to attend. It is a short, beautiful way to begin a day of practice.",
    img: 'images/2023/04/Other-ways-to-help-ceremony-at-the-Madonna.jpg'
  }
];

// ===== WELLNESS TREATMENTS =====
var TREATMENTS_DATA = [
  {
    id: 'treatment-swedish-massage',
    type: 'treatment',
    title: 'Swedish Massage (Deep Flow)',
    practitioner: 'Registered Massage Therapists',
    durations: [
      { time: '60 minutes', price: '$120' },
      { time: '90 minutes', price: '$180' }
    ],
    desc: 'Classic therapeutic bodywork tailored to your needs. Releases tension, improves circulation, and restores ease throughout the body.',
    longDesc: 'Swedish Massage (Deep Flow) is classic therapeutic bodywork using long, flowing strokes and focused pressure to release muscle tension, improve circulation, and restore ease throughout the body. Each session is tailored to your needs. Suitable for those looking for relaxation, recovery, or relief from chronic tension.',
    img: 'images/2023/01/Registered-RMT-massage-Canva-Pro-stock-photo-2023.jpg'
  },
  {
    id: 'treatment-maha-therapy',
    type: 'treatment',
    title: 'The MAHA Therapy',
    practitioner: 'Savita Leah Young (Ayurveda, 40+ years)',
    durations: [ { time: '150 minutes', price: '$270' } ],
    desc: "The Centre's signature treatment. A 150-minute journey combining Abhyanga oil massage, Swedana herbal steam, Udtana herbal paste exfoliation, and Shirodhara warm oil therapy.",
    longDesc: "The MAHA Therapy is the Centre's signature wellness treatment, offered by Savita Leah Young. Over 150 minutes, it combines four classical Ayurvedic therapies: Abhyanga (warm oil massage), Swedana (herbal steam), Udtana (herbal paste exfoliation), and Shirodhara (warm oil stream on the forehead). The result is a deeply nourishing, multi-layered experience that leaves the body, mind, and nervous system profoundly restored.",
    img: 'images/2023/01/2023-Savita-Leah-Young-Wellness-Treatments.jpg'
  },
  {
    id: 'treatment-abhyanga',
    type: 'treatment',
    title: 'Abhyanga (Ayurvedic Oil Massage)',
    practitioner: 'Savita Leah Young',
    durations: [ { time: '75 minutes', price: '$160' } ],
    desc: 'Our most popular treatment. Warm herbal oils are applied in long, flowing strokes to nourish the skin, calm the nervous system, and balance the doshas.',
    longDesc: 'Abhyanga is the classical Ayurvedic oil massage and one of the most requested treatments at the Centre. Warm herbal oils - chosen for your constitution - are applied in long, flowing strokes along the meridians of the body. The practice nourishes the skin, calms the nervous system, improves circulation, and balances the doshas. Allow time to rest after the treatment.',
    img: 'images/2021/12/serene.jpg'
  },
  {
    id: 'treatment-swedana',
    type: 'treatment',
    title: 'Swedana (Herbal Steam)',
    practitioner: 'Savita Leah Young',
    durations: [
      { time: '60 minutes', price: '$128' },
      { time: '90 minutes', price: '$180' },
      { time: '30 min add-on', price: '$60' }
    ],
    desc: 'A medicated steam treatment that opens the channels, draws toxins to the surface, and deeply relaxes the musculature.',
    longDesc: 'Swedana is the Ayurvedic medicated steam treatment. Herbal decoctions are infused into warm steam that gently opens the channels of the body, draws toxins to the surface, and deeply relaxes the musculature. Available as a standalone treatment or as an add-on following an oil massage.',
    img: 'images/2022/01/buddha-background.jpg'
  },
  {
    id: 'treatment-shirodhara',
    type: 'treatment',
    title: 'Shirodhara (Oil Therapy)',
    practitioner: 'Savita Leah Young',
    durations: [
      { time: '60 minutes', price: '$120' },
      { time: '90 minutes', price: '$180' }
    ],
    desc: 'A continuous stream of warm oil flows over the forehead, settling the mind into a meditative stillness. Deeply restorative for stress, insomnia, and mental fatigue.',
    longDesc: "Shirodhara is one of the most profound treatments in the Ayurvedic tradition. A continuous stream of warm, herb-infused oil flows over the 'third eye' on the forehead, settling the nervous system into a deeply meditative stillness. The treatment is especially restorative for stress, insomnia, anxiety, mental fatigue, and the subtle fog that comes with prolonged overwhelm.",
    img: 'images/2021/12/Fountain.jpg'
  },
  {
    id: 'treatment-acupuncture',
    type: 'treatment',
    title: 'Acupuncture (Initial Visit)',
    practitioner: 'Ehlana Helen (Traditional Chinese Medicine)',
    durations: [ { time: '90 minutes', price: '$140' } ],
    desc: 'Comprehensive intake and treatment with Ehlana Helen. Traditional Chinese medicine diagnostics combined with a yoga-informed understanding of the body.',
    longDesc: 'Your initial acupuncture visit with Ehlana Helen includes a comprehensive intake, pulse and tongue diagnostics, and a full treatment. Ehlana combines classical Traditional Chinese Medicine with a yoga-informed understanding of the body. Follow-up visits are shorter and focused on continued care. Booking via jane app.',
    bookUrl: 'https://sattvaacupunctureandyoga.janeapp.com',
    img: 'images/2025/10/needles-accupuncture.avif'
  },
  {
    id: 'treatment-bodywork',
    type: 'treatment',
    title: 'Bodywork / Needle-Free',
    practitioner: 'Ehlana Helen',
    durations: [ { time: '60 minutes', price: '$100' } ],
    desc: 'Therapeutic bodywork using acupressure, craniosacral, and other non-invasive modalities. Ideal for those who prefer treatment without needles.',
    longDesc: 'Needle-Free Bodywork is for those who prefer hands-on therapy without acupuncture needles. Ehlana draws from acupressure, craniosacral work, myofascial release, and other non-invasive modalities to address tension, pain, and energetic imbalance. A gentler option that still accesses deep therapeutic benefit.',
    bookUrl: 'https://sattvaacupunctureandyoga.janeapp.com',
    img: 'images/2022/03/Tree-Pose-in-Boots-scaled-1.jpg'
  },
  {
    id: 'treatment-fire-cupping',
    type: 'treatment',
    title: 'Fire Cupping',
    practitioner: 'Ehlana Helen',
    durations: [ { time: '45 minutes', price: '$75' } ],
    desc: "Traditional cupping therapy to release deep-seated tension, improve circulation, and support the body's natural healing processes.",
    longDesc: 'Fire Cupping is a traditional Chinese medicine therapy that uses gentle suction to lift muscle and fascia, release deep-seated tension, improve circulation, and stimulate the flow of qi. A beautiful complement to acupuncture or as a standalone treatment for chronic tightness, especially in the back and shoulders.',
    bookUrl: 'https://sattvaacupunctureandyoga.janeapp.com',
    img: 'images/2022/03/Holy-Mother-below-fountain.jpg'
  },
  {
    id: 'treatment-wood-fired-sauna',
    type: 'treatment',
    title: 'Wood-Fired Sauna',
    practitioner: 'Self-directed booking',
    durations: [ { time: '2 hours (2-8 people)', price: '$100' }, { time: 'Additional hour', price: '+$50' } ],
    desc: 'Private sauna sessions for 2 to 8 people. Nestled in the forest, heated by wood fire. A cleansing and social experience in a beautiful natural setting.',
    longDesc: 'The wood-fired sauna at the Centre is nestled in the forest and heated the traditional way. Rent the space privately for 2 to 8 people. A beautiful cleansing experience whether used for solo reflection, a quiet soak with a friend, or a small group gathering. Towels provided. Cold plunge access included.',
    img: 'images/2021/12/Sauna-at-night.jpg'
  },
  {
    id: 'treatment-reset-rejuvenate',
    type: 'treatment',
    title: 'Reset & Rejuvenate with Ayurveda',
    practitioner: 'Savita Leah Young',
    durations: [ { time: 'By consultation', price: 'Inquire' } ],
    desc: 'A specialized Ayurvedic program designed for individuals in cancer remission. Gentle, restorative treatments and dietary guidance to support recovery, rebuild strength, and nourish the whole person.',
    longDesc: 'Reset & Rejuvenate with Ayurveda is a specialized program designed with deep care for individuals in cancer remission or recovering from serious illness. Savita Leah Young draws on 40+ years of Ayurvedic practice to create a customized combination of gentle, restorative treatments, dietary guidance, and rhythm-of-life recommendations. The program supports recovery, rebuilds strength, and nourishes the whole person. By consultation only.',
    img: 'images/2022/09/Lotus-photo-jpeg.jpg'
  }
];

// ===== COMBINED: single OFFERINGS array for lookups =====
var OFFERINGS = EVENTS.concat(CLASSES_DATA).concat(COMMUNITY_DATA).concat(TREATMENTS_DATA);

// Each entry gets a URL to its dedicated detail page
OFFERINGS.forEach(function(o) { o.url = 'event.html?id=' + o.id; });
